# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main
    paths:
      - 'dbscripts/deploy/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  LBJobDockerCLI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '1.8'
          distribution: 'adopt'
      - name: Run 'Liquibase status' in a Docker container
        uses: docker://liquibase/liquibase:latest
        with:
          args: --driver=org.h2.Driver --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=/dbscripts/masterChangelog.xml --username=admin --password=password status --verbose

      # Runs a set of commands using the runners shell
      - name: Run 'Liquibase update' in a Docker container
        uses: docker://liquibase/liquibase:latest
        with:
          args: --driver=org.h2.Driver --url="jdbc:h2:mem:liquibase_dev" --changeLogFile=/dbscripts/masterChangelog.xml --username=admin --password=password --logLevel=debug update
